//
//  PayTables.swift
//  VideoPoker
//
//  Pay tables for all games. Each game has a base table (which defines the
//  paylines and how hand values are grouped into them), and each pay schedule
//  overrides the base table's payouts.
//
//  Copyright 2010-2011 Mike McQueen. All rights reserved.
//

enum PayTables {

    static let jacksOrBetterBase: [Payline] = [
        Payline(.royalFlush, 250, 4000),
        Payline(.straightFlush, 50),
        Payline(.fourOfAKind, 25),
        Payline(.fullHouse, 9),
        Payline(.flush, 6),
        Payline(.straight, 4),
        Payline(.threeKind, 3),
        Payline(.twoPair, 2),
        Payline(.jacksOrBetter, 1, flags: .group),
        Payline(.pairOfJacks, 0),
        Payline(.pairOfQueens, 0),
        Payline(.pairOfKings, 0),
        Payline(.pairOfAces, 0, flags: .group),
    ]

    static let bonusPokerBase: [Payline] = [
        Payline(.royalFlush, 0),
        Payline(.straightFlush, 0),
        Payline(.fourAces, 0),
        Payline(.four2s3s4s, 0, flags: .group),
        Payline(.fourTwos, 0),
        Payline(.fourThrees, 0),
        Payline(.fourFours, 0, flags: .group),
        Payline(.four5sThruKings, 0, flags: .group),
        Payline(.fourFives, 0),
        Payline(.fourSixes, 0),
        Payline(.fourSevens, 0),
        Payline(.fourEights, 0),
        Payline(.fourNines, 0),
        Payline(.fourTens, 0),
        Payline(.fourJacks, 0),
        Payline(.fourQueens, 0),
        Payline(.fourKings, 0, flags: .group),
        Payline(.fullHouse, 0),
        Payline(.flush, 0),
        Payline(.straight, 0),
        Payline(.threeKind, 0),
        Payline(.twoPair, 0),
        Payline(.jacksOrBetter, 0, flags: .group),
        Payline(.pairOfJacks, 0),
        Payline(.pairOfQueens, 0),
        Payline(.pairOfKings, 0),
        Payline(.pairOfAces, 0, flags: .group),
    ]

    static let doubleDoubleBonusBase: [Payline] = [
        Payline(.royalFlush, 0),
        Payline(.straightFlush, 0),
        Payline(.fourAcesWith234, 0, flags: .group),
        Payline(.fourAcesWithTwo, 0),
        Payline(.fourAcesWithThree, 0),
        Payline(.fourAcesWithFour, 0, flags: .group),
        Payline(.four2s3s4sWithAce234, 0, flags: .group),
        Payline(.fourTwosWithAce, 0),
        Payline(.fourTwosWithThree, 0),
        Payline(.fourTwosWithFour, 0),
        Payline(.fourThreesWithAce, 0),
        Payline(.fourThreesWithTwo, 0),
        Payline(.fourThreesWithFour, 0),
        Payline(.fourFoursWithAce, 0),
        Payline(.fourFoursWithTwo, 0),
        Payline(.fourFoursWithThree, 0, flags: .group),
        Payline(.fourAces, 0),
        Payline(.four2s3s4s, 0, flags: .group),
        Payline(.fourTwos, 0),
        Payline(.fourThrees, 0),
        Payline(.fourFours, 0, flags: .group),
        Payline(.four5sThruKings, 0, flags: .group),
        Payline(.fourFives, 0),
        Payline(.fourSixes, 0),
        Payline(.fourSevens, 0),
        Payline(.fourEights, 0),
        Payline(.fourNines, 0),
        Payline(.fourTens, 0),
        Payline(.fourJacks, 0),
        Payline(.fourQueens, 0),
        Payline(.fourKings, 0, flags: .group),
        Payline(.fullHouse, 0),
        Payline(.flush, 0),
        Payline(.straight, 0),
        Payline(.threeKind, 0),
        Payline(.twoPair, 0),
        Payline(.jacksOrBetter, 0, flags: .group),
        Payline(.pairOfJacks, 0),
        Payline(.pairOfQueens, 0),
        Payline(.pairOfKings, 0),
        Payline(.pairOfAces, 0, flags: .group),
    ]

    static let tripleDoubleBonusBase: [Payline] = [
        Payline(.royalFlush, 0),
        Payline(.fourAcesWith234, 0, flags: .group),
        Payline(.fourAcesWithTwo, 0),
        Payline(.fourAcesWithThree, 0),
        Payline(.fourAcesWithFour, 0, flags: .group),
        Payline(.four2s3s4sWithAce234, 0, flags: .group),
        Payline(.fourTwosWithAce, 0),
        Payline(.fourTwosWithThree, 0),
        Payline(.fourTwosWithFour, 0),
        Payline(.fourThreesWithAce, 0),
        Payline(.fourThreesWithTwo, 0),
        Payline(.fourThreesWithFour, 0),
        Payline(.fourFoursWithAce, 0),
        Payline(.fourFoursWithTwo, 0),
        Payline(.fourFoursWithThree, 0, flags: .group),
        Payline(.fourAces, 0),
        Payline(.four2s3s4s, 0, flags: .group),
        Payline(.fourTwos, 0),
        Payline(.fourThrees, 0),
        Payline(.fourFours, 0, flags: .group),
        Payline(.four5sThruKings, 0, flags: .group),
        Payline(.fourFives, 0),
        Payline(.fourSixes, 0),
        Payline(.fourSevens, 0),
        Payline(.fourEights, 0),
        Payline(.fourNines, 0),
        Payline(.fourTens, 0),
        Payline(.fourJacks, 0),
        Payline(.fourQueens, 0),
        Payline(.fourKings, 0, flags: .group),
        Payline(.straightFlush, 0),
        Payline(.fullHouse, 0),
        Payline(.flush, 0),
        Payline(.straight, 0),
        Payline(.threeKind, 0),
        Payline(.twoPair, 0),
        Payline(.jacksOrBetter, 0, flags: .group),
        Payline(.pairOfJacks, 0),
        Payline(.pairOfQueens, 0),
        Payline(.pairOfKings, 0),
        Payline(.pairOfAces, 0, flags: .group),
    ]

    static let deucesWildBase: [Payline] = [
        Payline(.royalFlushNoDeuces, 0, flags: .group),
        Payline(.royalFlush, 0, flags: [.group, .noWild]),
        Payline(.fourDeuces, 0),
        Payline(.royalFlushWithDeuce, 0, flags: .group),
        Payline(.royalFlushWild, 0, flags: .group),
        Payline(.fiveOfAKind, 0),
        Payline(.straightFlush, 0),
        Payline(.fourOfAKind, 0),
        Payline(.fullHouse, 0),
        Payline(.flush, 0),
        Payline(.straight, 0),
        Payline(.threeKind, 0),
    ]

    static let kingsOrBetterBase: [Payline] = [
        Payline(.royalFlushNoJokers, 0, flags: .group),
        Payline(.royalFlush, 0, flags: [.group, .noWild]),
        Payline(.fiveOfAKind, 0),
        Payline(.royalFlushWithJoker, 0, flags: .group),
        Payline(.royalFlushWild, 0, flags: .group),
        Payline(.straightFlush, 0),
        Payline(.fourOfAKind, 0),
        Payline(.fullHouse, 0),
        Payline(.flush, 0),
        Payline(.straight, 0),
        Payline(.threeKind, 0),
        Payline(.twoPair, 0),
        Payline(.kingsOrBetter, 0, flags: .group),
        Payline(.pairOfKings, 0),
        Payline(.pairOfAces, 0, flags: .group),
    ]

    static let games: [Game] = [
        Game(id: .allAmerican, name: "All American", solverFilename: "Jacks.dat", schedules: [
            PaySchedule(gameID: .allAmerican, base: jacksOrBetterBase, overrides: [
                Payline(.royalFlush, 250, 4000),
                Payline(.straightFlush, 200),
                Payline(.fourOfAKind, 40),
                Payline(.fullHouse, 8),
                Payline(.flush, 8),
                Payline(.straight, 8),
                Payline(.threeKind, 3),
                Payline(.twoPair, 1),
                Payline(.jacksOrBetter, 1),
            ], estimatedReturn: 100.72, wildCardNumber: 0),
            PaySchedule(gameID: .allAmerican, base: jacksOrBetterBase, overrides: [
                Payline(.royalFlush, 250, 4000),
                Payline(.straightFlush, 200),
                Payline(.fourOfAKind, 35),
                Payline(.fullHouse, 8),
                Payline(.flush, 8),
                Payline(.straight, 8),
                Payline(.threeKind, 3),
                Payline(.twoPair, 1),
                Payline(.jacksOrBetter, 1),
            ], estimatedReturn: 99.60, wildCardNumber: 0),
            PaySchedule(gameID: .allAmerican, base: jacksOrBetterBase, overrides: [
                Payline(.royalFlush, 250, 4000),
                Payline(.straightFlush, 200),
                Payline(.fourOfAKind, 30),
                Payline(.fullHouse, 8),
                Payline(.flush, 8),
                Payline(.straight, 8),
                Payline(.threeKind, 3),
                Payline(.twoPair, 1),
                Payline(.jacksOrBetter, 1),
            ], estimatedReturn: 98.49, wildCardNumber: 0),
        ]),
        Game(id: .bonusPoker, name: "BonusPoker", solverFilename: "Bonus.dat", schedules: [
            PaySchedule(gameID: .bonusPoker, base: bonusPokerBase, overrides: [
                Payline(.royalFlush, 250, 4000),
                Payline(.straightFlush, 50),
                Payline(.fourAces, 35),
                Payline(.four2s3s4s, 35),
                Payline(.four5sThruKings, 35),
                Payline(.fullHouse, 8),
                Payline(.flush, 5),
                Payline(.straight, 4),
                Payline(.threeKind, 3),
                Payline(.twoPair, 2),
                Payline(.jacksOrBetter, 1),
            ], estimatedReturn: 99.66, wildCardNumber: 0),
            PaySchedule(gameID: .bonusPoker, base: bonusPokerBase, overrides: [
                Payline(.royalFlush, 250, 4000),
                Payline(.straightFlush, 50),
                Payline(.fourAces, 80),
                Payline(.four2s3s4s, 40),
                Payline(.four5sThruKings, 20),
                Payline(.fullHouse, 9),
                Payline(.flush, 5),
                Payline(.straight, 4),
                Payline(.threeKind, 3),
                Payline(.twoPair, 2),
                Payline(.jacksOrBetter, 1),
            ], estimatedReturn: 99.50, wildCardNumber: 0),
            PaySchedule(gameID: .bonusPoker, base: bonusPokerBase, overrides: [
                Payline(.royalFlush, 250, 4000),
                Payline(.straightFlush, 50),
                Payline(.fourAces, 80),
                Payline(.four2s3s4s, 40),
                Payline(.four5sThruKings, 20),
                Payline(.fullHouse, 8),
                Payline(.flush, 6),
                Payline(.straight, 4),
                Payline(.threeKind, 3),
                Payline(.twoPair, 2),
                Payline(.jacksOrBetter, 1),
            ], estimatedReturn: 99.44, wildCardNumber: 0),
            PaySchedule(gameID: .bonusPoker, base: bonusPokerBase, overrides: [
                Payline(.royalFlush, 250, 4000),
                Payline(.straightFlush, 100),
                Payline(.fourAces, 200),
                Payline(.four2s3s4s, 40),
                Payline(.four5sThruKings, 25),
                Payline(.fullHouse, 12),
                Payline(.flush, 8),
                Payline(.straight, 5),
                Payline(.threeKind, 3),
                Payline(.twoPair, 1),
                Payline(.jacksOrBetter, 1),
            ], estimatedReturn: 99.36, wildCardNumber: 0),
            PaySchedule(gameID: .bonusPoker, base: bonusPokerBase, overrides: [
                Payline(.royalFlush, 250, 4000),
                Payline(.straightFlush, 50),
                Payline(.fourAces, 80),
                Payline(.four2s3s4s, 40),
                Payline(.four5sThruKings, 25),
                Payline(.fullHouse, 8),
                Payline(.flush, 5),
                Payline(.straight, 4),
                Payline(.threeKind, 3),
                Payline(.twoPair, 2),
                Payline(.jacksOrBetter, 1),
            ], estimatedReturn: 99.17, wildCardNumber: 0),
            PaySchedule(gameID: .bonusPoker, base: bonusPokerBase, overrides: [
                Payline(.royalFlush, 250, 4000),
                Payline(.straightFlush, 50),
                Payline(.fourAces, 75),
                Payline(.four2s3s4s, 40),
                Payline(.four5sThruKings, 25),
                Payline(.fullHouse, 8),
                Payline(.flush, 5),
                Payline(.straight, 4),
                Payline(.threeKind, 3),
                Payline(.twoPair, 2),
                Payline(.jacksOrBetter, 1),
            ], estimatedReturn: 99.07, wildCardNumber: 0),
            PaySchedule(gameID: .bonusPoker, base: bonusPokerBase, overrides: [
                Payline(.royalFlush, 250, 4000),
                Payline(.straightFlush, 50),
                Payline(.fourAces, 80),
                Payline(.four2s3s4s, 50),
                Payline(.four5sThruKings, 25),
                Payline(.fullHouse, 7),
                Payline(.flush, 5),
                Payline(.straight, 4),
                Payline(.threeKind, 3),
                Payline(.twoPair, 2),
                Payline(.jacksOrBetter, 1),
            ], estimatedReturn: 98.54, wildCardNumber: 0),
            PaySchedule(gameID: .bonusPoker, base: bonusPokerBase, overrides: [
                Payline(.royalFlush, 250, 4000),
                Payline(.straightFlush, 50),
                Payline(.fourAces, 30),
                Payline(.four2s3s4s, 30),
                Payline(.four5sThruKings, 30),
                Payline(.fullHouse, 8),
                Payline(.flush, 5),
                Payline(.straight, 4),
                Payline(.threeKind, 3),
                Payline(.twoPair, 2),
                Payline(.jacksOrBetter, 1),
            ], estimatedReturn: 98.48, wildCardNumber: 0),
            PaySchedule(gameID: .bonusPoker, base: bonusPokerBase, overrides: [
                Payline(.royalFlush, 250, 4000),
                Payline(.straightFlush, 50),
                Payline(.fourAces, 80),
                Payline(.four2s3s4s, 40),
                Payline(.four5sThruKings, 25),
                Payline(.fullHouse, 7),
                Payline(.flush, 5),
                Payline(.straight, 4),
                Payline(.threeKind, 3),
                Payline(.twoPair, 2),
                Payline(.jacksOrBetter, 1),
            ], estimatedReturn: 98.01, wildCardNumber: 0),
            PaySchedule(gameID: .bonusPoker, base: bonusPokerBase, overrides: [
                Payline(.royalFlush, 250, 4000),
                Payline(.straightFlush, 50),
                Payline(.fourAces, 35),
                Payline(.four2s3s4s, 35),
                Payline(.four5sThruKings, 35),
                Payline(.fullHouse, 6),
                Payline(.flush, 5),
                Payline(.straight, 4),
                Payline(.threeKind, 3),
                Payline(.twoPair, 2),
                Payline(.jacksOrBetter, 1),
            ], estimatedReturn: 97.36, wildCardNumber: 0),
        ]),
        Game(id: .bonusPokerDeluxe, name: "Bonus Poker Deluxe", solverFilename: "Jacks.dat", schedules: [
            PaySchedule(gameID: .bonusPokerDeluxe, base: jacksOrBetterBase, overrides: [
                Payline(.royalFlush, 250, 4000),
                Payline(.straightFlush, 50),
                Payline(.fourOfAKind, 80),
                Payline(.fullHouse, 9),
                Payline(.flush, 6),
                Payline(.straight, 4),
                Payline(.threeKind, 3),
                Payline(.twoPair, 1),
                Payline(.jacksOrBetter, 1),
            ], estimatedReturn: 99.64, wildCardNumber: 0),
            PaySchedule(gameID: .bonusPokerDeluxe, base: jacksOrBetterBase, overrides: [
                Payline(.royalFlush, 250, 4000),
                Payline(.straightFlush, 50),
                Payline(.fourOfAKind, 80),
                Payline(.fullHouse, 8),
                Payline(.flush, 6),
                Payline(.straight, 4),
                Payline(.threeKind, 3),
                Payline(.twoPair, 1),
                Payline(.jacksOrBetter, 1),
            ], estimatedReturn: 98.49, wildCardNumber: 0),
            PaySchedule(gameID: .bonusPokerDeluxe, base: jacksOrBetterBase, overrides: [
                Payline(.royalFlush, 250, 4000),
                Payline(.straightFlush, 50),
                Payline(.fourOfAKind, 80),
                Payline(.fullHouse, 8),
                Payline(.flush, 5),
                Payline(.straight, 4),
                Payline(.threeKind, 3),
                Payline(.twoPair, 1),
                Payline(.jacksOrBetter, 1),
            ], estimatedReturn: 97.40, wildCardNumber: 0),
            PaySchedule(gameID: .bonusPokerDeluxe, base: jacksOrBetterBase, overrides: [
                Payline(.royalFlush, 250, 4000),
                Payline(.straightFlush, 50),
                Payline(.fourOfAKind, 80),
                Payline(.fullHouse, 7),
                Payline(.flush, 5),
                Payline(.straight, 4),
                Payline(.threeKind, 3),
                Payline(.twoPair, 1),
                Payline(.jacksOrBetter, 1),
            ], estimatedReturn: 96.25, wildCardNumber: 0),
        ]),
        Game(id: .deucesWild, name: "Deuces Wild", solverFilename: "Deuces.dat", schedules: [
            PaySchedule(gameID: .deucesWild, base: deucesWildBase, overrides: [
                Payline(.royalFlushNoDeuces, 250, 4000),
                Payline(.fourDeuces, 200),
                Payline(.royalFlushWithDeuce, 25),
                Payline(.fiveOfAKind, 15),
                Payline(.straightFlush, 9),
                Payline(.fourOfAKind, 5),
                Payline(.fullHouse, 3),
                Payline(.flush, 2),
                Payline(.straight, 2),
                Payline(.threeKind, 1),
            ], estimatedReturn: 100.76, wildCardNumber: CardNumber.deuce),
            PaySchedule(gameID: .deucesWild, base: deucesWildBase, overrides: [
                Payline(.royalFlushNoDeuces, 250, 4000),
                Payline(.fourDeuces, 200),
                Payline(.royalFlushWithDeuce, 25),
                Payline(.fiveOfAKind, 15),
                Payline(.straightFlush, 11),
                Payline(.fourOfAKind, 4),
                Payline(.fullHouse, 4),
                Payline(.flush, 3),
                Payline(.straight, 2),
                Payline(.threeKind, 1),
            ], estimatedReturn: 99.96, wildCardNumber: CardNumber.deuce),
            PaySchedule(gameID: .deucesWild, base: deucesWildBase, overrides: [
                Payline(.royalFlushNoDeuces, 250, 4000),
                Payline(.fourDeuces, 200),
                Payline(.royalFlushWithDeuce, 25),
                Payline(.fiveOfAKind, 16),
                Payline(.straightFlush, 10),
                Payline(.fourOfAKind, 4),
                Payline(.fullHouse, 4),
                Payline(.flush, 3),
                Payline(.straight, 2),
                Payline(.threeKind, 1),
            ], estimatedReturn: 99.73, wildCardNumber: CardNumber.deuce),
            PaySchedule(gameID: .deucesWild, base: deucesWildBase, overrides: [
                Payline(.royalFlushNoDeuces, 250, 4000),
                Payline(.fourDeuces, 200),
                Payline(.royalFlushWithDeuce, 25),
                Payline(.fiveOfAKind, 15),
                Payline(.straightFlush, 10),
                Payline(.fourOfAKind, 4),
                Payline(.fullHouse, 4),
                Payline(.flush, 3),
                Payline(.straight, 2),
                Payline(.threeKind, 1),
            ], estimatedReturn: 99.42, wildCardNumber: CardNumber.deuce),
            PaySchedule(gameID: .deucesWild, base: deucesWildBase, overrides: [
                Payline(.royalFlushNoDeuces, 250, 4000),
                Payline(.fourDeuces, 200),
                Payline(.royalFlushWithDeuce, 25),
                Payline(.fiveOfAKind, 16),
                Payline(.straightFlush, 9),
                Payline(.fourOfAKind, 4),
                Payline(.fullHouse, 4),
                Payline(.flush, 3),
                Payline(.straight, 2),
                Payline(.threeKind, 1),
            ], estimatedReturn: 99.23, wildCardNumber: CardNumber.deuce),
            PaySchedule(gameID: .deucesWild, base: deucesWildBase, overrides: [
                Payline(.royalFlushNoDeuces, 250, 4000),
                Payline(.fourDeuces, 200),
                Payline(.royalFlushWithDeuce, 20),
                Payline(.fiveOfAKind, 12),
                Payline(.straightFlush, 9),
                Payline(.fourOfAKind, 5),
                Payline(.fullHouse, 3),
                Payline(.flush, 2),
                Payline(.straight, 2),
                Payline(.threeKind, 1),
            ], estimatedReturn: 98.94, wildCardNumber: CardNumber.deuce),
            PaySchedule(gameID: .deucesWild, base: deucesWildBase, overrides: [
                Payline(.royalFlushNoDeuces, 250, 4000),
                Payline(.fourDeuces, 200),
                Payline(.royalFlushWithDeuce, 25),
                Payline(.fiveOfAKind, 15),
                Payline(.straightFlush, 9),
                Payline(.fourOfAKind, 4),
                Payline(.fullHouse, 4),
                Payline(.flush, 3),
                Payline(.straight, 2),
                Payline(.threeKind, 1),
            ], estimatedReturn: 98.91, wildCardNumber: CardNumber.deuce),
            PaySchedule(gameID: .deucesWild, base: deucesWildBase, overrides: [
                Payline(.royalFlushNoDeuces, 250, 4000),
                Payline(.fourDeuces, 200),
                Payline(.royalFlushWithDeuce, 20),
                Payline(.fiveOfAKind, 15),
                Payline(.straightFlush, 9),
                Payline(.fourOfAKind, 4),
                Payline(.fullHouse, 4),
                Payline(.flush, 3),
                Payline(.straight, 2),
                Payline(.threeKind, 1),
            ], estimatedReturn: 97.97, wildCardNumber: CardNumber.deuce),
            PaySchedule(gameID: .deucesWild, base: deucesWildBase, overrides: [
                Payline(.royalFlushNoDeuces, 250, 4000),
                Payline(.fourDeuces, 200),
                Payline(.royalFlushWithDeuce, 20),
                Payline(.fiveOfAKind, 12),
                Payline(.straightFlush, 10),
                Payline(.fourOfAKind, 4),
                Payline(.fullHouse, 4),
                Payline(.flush, 3),
                Payline(.straight, 2),
                Payline(.threeKind, 1),
            ], estimatedReturn: 97.58, wildCardNumber: CardNumber.deuce),
            PaySchedule(gameID: .deucesWild, base: deucesWildBase, overrides: [
                Payline(.royalFlushNoDeuces, 250, 4000),
                Payline(.fourDeuces, 200),
                Payline(.royalFlushWithDeuce, 20),
                Payline(.fiveOfAKind, 12),
                Payline(.straightFlush, 9),
                Payline(.fourOfAKind, 4),
                Payline(.fullHouse, 4),
                Payline(.flush, 3),
                Payline(.straight, 2),
                Payline(.threeKind, 1),
            ], estimatedReturn: 97.06, wildCardNumber: CardNumber.deuce),
        ]),
        Game(id: .doubleBonus, name: "Double Bonus Poker", solverFilename: "Bonus.dat", schedules: [
            PaySchedule(gameID: .doubleBonus, base: bonusPokerBase, overrides: [
                Payline(.royalFlush, 250, 4796),
                Payline(.straightFlush, 50),
                Payline(.fourAces, 160),
                Payline(.four2s3s4s, 80),
                Payline(.four5sThruKings, 50),
                Payline(.fullHouse, 10),
                Payline(.flush, 7),
                Payline(.straight, 5),
                Payline(.threeKind, 3),
                Payline(.twoPair, 1),
                Payline(.jacksOrBetter, 1),
            ], estimatedReturn: 100.54, wildCardNumber: 0),
            PaySchedule(gameID: .doubleBonus, base: bonusPokerBase, overrides: [
                Payline(.royalFlush, 250, 4000),
                Payline(.straightFlush, 80),
                Payline(.fourAces, 160),
                Payline(.four2s3s4s, 80),
                Payline(.four5sThruKings, 50),
                Payline(.fullHouse, 10),
                Payline(.flush, 7),
                Payline(.straight, 5),
                Payline(.threeKind, 3),
                Payline(.twoPair, 1),
                Payline(.jacksOrBetter, 1),
            ], estimatedReturn: 100.52, wildCardNumber: 0),
            PaySchedule(gameID: .doubleBonus, base: bonusPokerBase, overrides: [
                Payline(.royalFlush, 250, 4000),
                Payline(.straightFlush, 50),
                Payline(.fourAces, 160),
                Payline(.four2s3s4s, 80),
                Payline(.four5sThruKings, 50),
                Payline(.fullHouse, 10),
                Payline(.flush, 7),
                Payline(.straight, 5),
                Payline(.threeKind, 3),
                Payline(.twoPair, 1),
                Payline(.jacksOrBetter, 1),
            ], estimatedReturn: 100.17, wildCardNumber: 0),
            PaySchedule(gameID: .doubleBonus, base: bonusPokerBase, overrides: [
                Payline(.royalFlush, 250, 4000),
                Payline(.straightFlush, 50),
                Payline(.fourAces, 160),
                Payline(.four2s3s4s, 80),
                Payline(.four5sThruKings, 50),
                Payline(.fullHouse, 12),
                Payline(.flush, 6),
                Payline(.straight, 5),
                Payline(.threeKind, 3),
                Payline(.twoPair, 1),
                Payline(.jacksOrBetter, 1),
            ], estimatedReturn: 99.76, wildCardNumber: 0),
        ]),
        Game(id: .doubleDblBonus, name: "Double Double Bonus", solverFilename: "DDBonus.dat", schedules: [
            PaySchedule(gameID: .doubleDblBonus, base: doubleDoubleBonusBase, overrides: [
                Payline(.royalFlush, 250, 4000),
                Payline(.straightFlush, 50),
                Payline(.fourAcesWith234, 400),
                Payline(.four2s3s4sWithAce234, 160),
                Payline(.fourAces, 160),
                Payline(.four2s3s4s, 80),
                Payline(.four5sThruKings, 50),
                Payline(.fullHouse, 10),
                Payline(.flush, 6),
                Payline(.straight, 4),
                Payline(.threeKind, 3),
                Payline(.twoPair, 1),
                Payline(.jacksOrBetter, 1),
            ], estimatedReturn: 100.07, wildCardNumber: 0),
            PaySchedule(gameID: .doubleDblBonus, base: doubleDoubleBonusBase, overrides: [
                Payline(.royalFlush, 250, 4000),
                Payline(.straightFlush, 40),
                Payline(.fourAcesWith234, 400),
                Payline(.four2s3s4sWithAce234, 160),
                Payline(.fourAces, 160),
                Payline(.four2s3s4s, 80),
                Payline(.four5sThruKings, 50),
                Payline(.fullHouse, 10),
                Payline(.flush, 6),
                Payline(.straight, 4),
                Payline(.threeKind, 3),
                Payline(.twoPair, 1),
                Payline(.jacksOrBetter, 1),
            ], estimatedReturn: 99.96, wildCardNumber: 0),
            PaySchedule(gameID: .doubleDblBonus, base: doubleDoubleBonusBase, overrides: [
                Payline(.royalFlush, 250, 4000),
                Payline(.straightFlush, 50),
                Payline(.fourAcesWith234, 400),
                Payline(.four2s3s4sWithAce234, 160),
                Payline(.fourAces, 160),
                Payline(.four2s3s4s, 80),
                Payline(.four5sThruKings, 45),
                Payline(.fullHouse, 10),
                Payline(.flush, 6),
                Payline(.straight, 4),
                Payline(.threeKind, 3),
                Payline(.twoPair, 1),
                Payline(.jacksOrBetter, 1),
            ], estimatedReturn: 98.98, wildCardNumber: 0),
            PaySchedule(gameID: .doubleDblBonus, base: doubleDoubleBonusBase, overrides: [
                Payline(.royalFlush, 250, 4000),
                Payline(.straightFlush, 50),
                Payline(.fourAcesWith234, 400),
                Payline(.four2s3s4sWithAce234, 160),
                Payline(.fourAces, 160),
                Payline(.four2s3s4s, 80),
                Payline(.four5sThruKings, 50),
                Payline(.fullHouse, 8),
                Payline(.flush, 6),
                Payline(.straight, 4),
                Payline(.threeKind, 3),
                Payline(.twoPair, 1),
                Payline(.jacksOrBetter, 1),
            ], estimatedReturn: 97.89, wildCardNumber: 0),
            PaySchedule(gameID: .doubleDblBonus, base: doubleDoubleBonusBase, overrides: [
                Payline(.royalFlush, 250, 4000),
                Payline(.straightFlush, 50),
                Payline(.fourAcesWith234, 400),
                Payline(.four2s3s4sWithAce234, 160),
                Payline(.fourAces, 160),
                Payline(.four2s3s4s, 80),
                Payline(.four5sThruKings, 50),
                Payline(.fullHouse, 9),
                Payline(.flush, 5),
                Payline(.straight, 4),
                Payline(.threeKind, 3),
                Payline(.twoPair, 1),
                Payline(.jacksOrBetter, 1),
            ], estimatedReturn: 97.87, wildCardNumber: 0),
        ]),
        Game(id: .doubleDeuces, name: "Double Deuces", solverFilename: "Deuces.dat", schedules: [
            PaySchedule(gameID: .doubleDeuces, base: deucesWildBase, overrides: [
                Payline(.royalFlushNoDeuces, 250, 4000),
                Payline(.fourDeuces, 400),
                Payline(.royalFlushWithDeuce, 20),
                Payline(.fiveOfAKind, 10),
                Payline(.straightFlush, 10),
                Payline(.fourOfAKind, 4),
                Payline(.fullHouse, 4),
                Payline(.flush, 3),
                Payline(.straight, 2),
                Payline(.threeKind, 1),
            ], estimatedReturn: 100.95, wildCardNumber: CardNumber.deuce),
            PaySchedule(gameID: .doubleDeuces, base: deucesWildBase, overrides: [
                Payline(.royalFlushNoDeuces, 250, 4700),
                Payline(.fourDeuces, 400),
                Payline(.royalFlushWithDeuce, 25),
                Payline(.fiveOfAKind, 16),
                Payline(.straightFlush, 13),
                Payline(.fourOfAKind, 4),
                Payline(.fullHouse, 3),
                Payline(.flush, 2),
                Payline(.straight, 2),
                Payline(.threeKind, 1),
            ], estimatedReturn: 100.92, wildCardNumber: CardNumber.deuce),
            PaySchedule(gameID: .doubleDeuces, base: deucesWildBase, overrides: [
                Payline(.royalFlushNoDeuces, 250, 4000),
                Payline(.fourDeuces, 400),
                Payline(.royalFlushWithDeuce, 25),
                Payline(.fiveOfAKind, 16),
                Payline(.straightFlush, 13),
                Payline(.fourOfAKind, 4),
                Payline(.fullHouse, 3),
                Payline(.flush, 2),
                Payline(.straight, 2),
                Payline(.threeKind, 1),
            ], estimatedReturn: 100.61, wildCardNumber: CardNumber.deuce),
            PaySchedule(gameID: .doubleDeuces, base: deucesWildBase, overrides: [
                Payline(.royalFlushNoDeuces, 250, 4000),
                Payline(.fourDeuces, 400),
                Payline(.royalFlushWithDeuce, 25),
                Payline(.fiveOfAKind, 16),
                Payline(.straightFlush, 12),
                Payline(.fourOfAKind, 4),
                Payline(.fullHouse, 3),
                Payline(.flush, 2),
                Payline(.straight, 2),
                Payline(.threeKind, 1),
            ], estimatedReturn: 100.09, wildCardNumber: CardNumber.deuce),
            PaySchedule(gameID: .doubleDeuces, base: deucesWildBase, overrides: [
                Payline(.royalFlushNoDeuces, 250, 4700),
                Payline(.fourDeuces, 400),
                Payline(.royalFlushWithDeuce, 25),
                Payline(.fiveOfAKind, 16),
                Payline(.straightFlush, 11),
                Payline(.fourOfAKind, 4),
                Payline(.fullHouse, 3),
                Payline(.flush, 2),
                Payline(.straight, 2),
                Payline(.threeKind, 1),
            ], estimatedReturn: 99.94, wildCardNumber: CardNumber.deuce),
            PaySchedule(gameID: .doubleDeuces, base: deucesWildBase, overrides: [
                Payline(.royalFlushNoDeuces, 250, 4000),
                Payline(.fourDeuces, 400),
                Payline(.royalFlushWithDeuce, 25),
                Payline(.fiveOfAKind, 15),
                Payline(.straightFlush, 12),
                Payline(.fourOfAKind, 4),
                Payline(.fullHouse, 3),
                Payline(.flush, 2),
                Payline(.straight, 2),
                Payline(.threeKind, 1),
            ], estimatedReturn: 99.78, wildCardNumber: CardNumber.deuce),
            PaySchedule(gameID: .doubleDeuces, base: deucesWildBase, overrides: [
                Payline(.royalFlushNoDeuces, 250, 4700),
                Payline(.fourDeuces, 400),
                Payline(.royalFlushWithDeuce, 25),
                Payline(.fiveOfAKind, 16),
                Payline(.straightFlush, 11),
                Payline(.fourOfAKind, 4),
                Payline(.fullHouse, 3),
                Payline(.flush, 2),
                Payline(.straight, 2),
                Payline(.threeKind, 1),
            ], estimatedReturn: 99.62, wildCardNumber: CardNumber.deuce),
            PaySchedule(gameID: .doubleDeuces, base: deucesWildBase, overrides: [
                Payline(.royalFlushNoDeuces, 250, 4700),
                Payline(.fourDeuces, 400),
                Payline(.royalFlushWithDeuce, 25),
                Payline(.fiveOfAKind, 16),
                Payline(.straightFlush, 10),
                Payline(.fourOfAKind, 4),
                Payline(.fullHouse, 3),
                Payline(.flush, 2),
                Payline(.straight, 2),
                Payline(.threeKind, 1),
            ], estimatedReturn: 99.17, wildCardNumber: CardNumber.deuce),
            PaySchedule(gameID: .doubleDeuces, base: deucesWildBase, overrides: [
                Payline(.royalFlushNoDeuces, 250, 4000),
                Payline(.fourDeuces, 400),
                Payline(.royalFlushWithDeuce, 25),
                Payline(.fiveOfAKind, 15),
                Payline(.straightFlush, 10),
                Payline(.fourOfAKind, 4),
                Payline(.fullHouse, 3),
                Payline(.flush, 2),
                Payline(.straight, 2),
                Payline(.threeKind, 1),
            ], estimatedReturn: 98.86, wildCardNumber: CardNumber.deuce),
        ]),
        Game(id: .jacksOrBetter, name: "Jacks or Better", solverFilename: "Jacks.dat", schedules: [
            PaySchedule(gameID: .jacksOrBetter, base: jacksOrBetterBase, overrides: [
                Payline(.royalFlush, 250, 4880),
                Payline(.straightFlush, 50),
                Payline(.fourOfAKind, 25),
                Payline(.fullHouse, 9),
                Payline(.flush, 6),
                Payline(.straight, 4),
                Payline(.threeKind, 3),
                Payline(.twoPair, 2),
                Payline(.jacksOrBetter, 1),
            ], estimatedReturn: 100.00, wildCardNumber: 0),
            PaySchedule(gameID: .jacksOrBetter, base: jacksOrBetterBase, overrides: [
                Payline(.royalFlush, 250, 4000),
                Payline(.straightFlush, 50),
                Payline(.fourOfAKind, 25),
                Payline(.fullHouse, 9),
                Payline(.flush, 6),
                Payline(.straight, 4),
                Payline(.threeKind, 3),
                Payline(.twoPair, 2),
                Payline(.jacksOrBetter, 1),
            ], estimatedReturn: 99.54, wildCardNumber: 0),
            PaySchedule(gameID: .jacksOrBetter, base: jacksOrBetterBase, overrides: [
                Payline(.royalFlush, 250, 4000),
                Payline(.straightFlush, 50),
                Payline(.fourOfAKind, 25),
                Payline(.fullHouse, 9),
                Payline(.flush, 5),
                Payline(.straight, 4),
                Payline(.threeKind, 3),
                Payline(.twoPair, 2),
                Payline(.jacksOrBetter, 1),
            ], estimatedReturn: 98.44, wildCardNumber: 0),
            PaySchedule(gameID: .jacksOrBetter, base: jacksOrBetterBase, overrides: [
                Payline(.royalFlush, 250, 4000),
                Payline(.straightFlush, 50),
                Payline(.fourOfAKind, 25),
                Payline(.fullHouse, 8),
                Payline(.flush, 6),
                Payline(.straight, 4),
                Payline(.threeKind, 3),
                Payline(.twoPair, 2),
                Payline(.jacksOrBetter, 1),
            ], estimatedReturn: 98.39, wildCardNumber: 0),
            PaySchedule(gameID: .jacksOrBetter, base: jacksOrBetterBase, overrides: [
                Payline(.royalFlush, 250, 4000),
                Payline(.straightFlush, 50),
                Payline(.fourOfAKind, 25),
                Payline(.fullHouse, 8),
                Payline(.flush, 5),
                Payline(.straight, 4),
                Payline(.threeKind, 3),
                Payline(.twoPair, 2),
                Payline(.jacksOrBetter, 1),
            ], estimatedReturn: 97.29, wildCardNumber: 0),
            PaySchedule(gameID: .jacksOrBetter, base: jacksOrBetterBase, overrides: [
                Payline(.royalFlush, 250, 4000),
                Payline(.straightFlush, 50),
                Payline(.fourOfAKind, 25),
                Payline(.fullHouse, 7),
                Payline(.flush, 6),
                Payline(.straight, 4),
                Payline(.threeKind, 3),
                Payline(.twoPair, 2),
                Payline(.jacksOrBetter, 1),
            ], estimatedReturn: 97.24, wildCardNumber: 0),
            PaySchedule(gameID: .jacksOrBetter, base: jacksOrBetterBase, overrides: [
                Payline(.royalFlush, 250, 4000),
                Payline(.straightFlush, 50),
                Payline(.fourOfAKind, 25),
                Payline(.fullHouse, 7),
                Payline(.flush, 5),
                Payline(.straight, 4),
                Payline(.threeKind, 3),
                Payline(.twoPair, 2),
                Payline(.jacksOrBetter, 1),
            ], estimatedReturn: 96.14, wildCardNumber: 0),
            PaySchedule(gameID: .jacksOrBetter, base: jacksOrBetterBase, overrides: [
                Payline(.royalFlush, 250, 4000),
                Payline(.straightFlush, 50),
                Payline(.fourOfAKind, 25),
                Payline(.fullHouse, 6),
                Payline(.flush, 5),
                Payline(.straight, 4),
                Payline(.threeKind, 3),
                Payline(.twoPair, 2),
                Payline(.jacksOrBetter, 1),
            ], estimatedReturn: 94.99, wildCardNumber: 0),
        ]),
        Game(id: .jokersWild, name: "Jokers Wild", solverFilename: "Jokers.dat", deckSize: 53, schedules: [
            PaySchedule(gameID: .jokersWild, base: kingsOrBetterBase, overrides: [
                Payline(.royalFlushNoJokers, 250, 4700),
                Payline(.fiveOfAKind, 200),
                Payline(.royalFlushWithJoker, 100),
                Payline(.straightFlush, 50),
                Payline(.fourOfAKind, 20),
                Payline(.fullHouse, 7),
                Payline(.flush, 5),
                Payline(.straight, 3),
                Payline(.threeKind, 2),
                Payline(.twoPair, 1),
                Payline(.kingsOrBetter, 1),
            ], estimatedReturn: 101.00, wildCardNumber: CardNumber.joker),
            PaySchedule(gameID: .jokersWild, base: kingsOrBetterBase, overrides: [
                Payline(.royalFlushNoJokers, 250, 4000),
                Payline(.fiveOfAKind, 200),
                Payline(.royalFlushWithJoker, 100),
                Payline(.straightFlush, 50),
                Payline(.fourOfAKind, 20),
                Payline(.fullHouse, 7),
                Payline(.flush, 5),
                Payline(.straight, 3),
                Payline(.threeKind, 2),
                Payline(.twoPair, 1),
                Payline(.kingsOrBetter, 1),
            ], estimatedReturn: 100.65, wildCardNumber: CardNumber.joker),
            PaySchedule(gameID: .jokersWild, base: kingsOrBetterBase, overrides: [
                Payline(.royalFlushNoJokers, 250, 4000),
                Payline(.fiveOfAKind, 200),
                Payline(.royalFlushWithJoker, 100),
                Payline(.straightFlush, 50),
                Payline(.fourOfAKind, 18),
                Payline(.fullHouse, 7),
                Payline(.flush, 5),
                Payline(.straight, 3),
                Payline(.threeKind, 2),
                Payline(.twoPair, 1),
                Payline(.kingsOrBetter, 1),
            ], estimatedReturn: 99.29, wildCardNumber: CardNumber.joker),
            PaySchedule(gameID: .jokersWild, base: kingsOrBetterBase, overrides: [
                Payline(.royalFlushNoJokers, 250, 4000),
                Payline(.fiveOfAKind, 200),
                Payline(.royalFlushWithJoker, 100),
                Payline(.straightFlush, 50),
                Payline(.fourOfAKind, 20),
                Payline(.fullHouse, 6),
                Payline(.flush, 5),
                Payline(.straight, 3),
                Payline(.threeKind, 2),
                Payline(.twoPair, 1),
                Payline(.kingsOrBetter, 1),
            ], estimatedReturn: 99.08, wildCardNumber: CardNumber.joker),
            PaySchedule(gameID: .jokersWild, base: kingsOrBetterBase, overrides: [
                Payline(.royalFlushNoJokers, 250, 4000),
                Payline(.fiveOfAKind, 200),
                Payline(.royalFlushWithJoker, 100),
                Payline(.straightFlush, 50),
                Payline(.fourOfAKind, 18),
                Payline(.fullHouse, 7),
                Payline(.flush, 5),
                Payline(.straight, 3),
                Payline(.threeKind, 2),
                Payline(.twoPair, 1),
                Payline(.kingsOrBetter, 1),
            ], estimatedReturn: 98.94, wildCardNumber: CardNumber.joker),
            PaySchedule(gameID: .jokersWild, base: kingsOrBetterBase, overrides: [
                Payline(.royalFlushNoJokers, 250, 4700),
                Payline(.fiveOfAKind, 200),
                Payline(.royalFlushWithJoker, 100),
                Payline(.straightFlush, 50),
                Payline(.fourOfAKind, 17),
                Payline(.fullHouse, 7),
                Payline(.flush, 5),
                Payline(.straight, 3),
                Payline(.threeKind, 2),
                Payline(.twoPair, 1),
                Payline(.kingsOrBetter, 1),
            ], estimatedReturn: 98.44, wildCardNumber: CardNumber.joker),
            PaySchedule(gameID: .jokersWild, base: kingsOrBetterBase, overrides: [
                Payline(.royalFlushNoJokers, 250, 4000),
                Payline(.fiveOfAKind, 200),
                Payline(.royalFlushWithJoker, 100),
                Payline(.straightFlush, 50),
                Payline(.fourOfAKind, 17),
                Payline(.fullHouse, 7),
                Payline(.flush, 5),
                Payline(.straight, 3),
                Payline(.threeKind, 2),
                Payline(.twoPair, 1),
                Payline(.kingsOrBetter, 1),
            ], estimatedReturn: 98.09, wildCardNumber: CardNumber.joker),
            PaySchedule(gameID: .jokersWild, base: kingsOrBetterBase, overrides: [
                Payline(.royalFlushNoJokers, 250, 4000),
                Payline(.fiveOfAKind, 200),
                Payline(.royalFlushWithJoker, 100),
                Payline(.straightFlush, 50),
                Payline(.fourOfAKind, 15),
                Payline(.fullHouse, 8),
                Payline(.flush, 5),
                Payline(.straight, 3),
                Payline(.threeKind, 2),
                Payline(.twoPair, 1),
                Payline(.kingsOrBetter, 1),
            ], estimatedReturn: 97.95, wildCardNumber: CardNumber.joker),
        ]),
        Game(id: .looseDeuces, name: "Loose Deuces", solverFilename: "Deuces.dat", schedules: [
            PaySchedule(gameID: .looseDeuces, base: deucesWildBase, overrides: [
                Payline(.royalFlushNoDeuces, 250, 4000),
                Payline(.fourDeuces, 500),
                Payline(.royalFlushWithDeuce, 25),
                Payline(.fiveOfAKind, 16),
                Payline(.straightFlush, 11),
                Payline(.fourOfAKind, 4),
                Payline(.fullHouse, 3),
                Payline(.flush, 2),
                Payline(.straight, 2),
                Payline(.threeKind, 1),
            ], estimatedReturn: 101.73, wildCardNumber: CardNumber.deuce),
            PaySchedule(gameID: .looseDeuces, base: deucesWildBase, overrides: [
                Payline(.royalFlushNoDeuces, 250, 4000),
                Payline(.fourDeuces, 500),
                Payline(.royalFlushWithDeuce, 25),
                Payline(.fiveOfAKind, 17),
                Payline(.straightFlush, 10),
                Payline(.fourOfAKind, 4),
                Payline(.fullHouse, 3),
                Payline(.flush, 2),
                Payline(.straight, 2),
                Payline(.threeKind, 1),
            ], estimatedReturn: 101.60, wildCardNumber: CardNumber.deuce),
            PaySchedule(gameID: .looseDeuces, base: deucesWildBase, overrides: [
                Payline(.royalFlushNoDeuces, 250, 4000),
                Payline(.fourDeuces, 500),
                Payline(.royalFlushWithDeuce, 25),
                Payline(.fiveOfAKind, 16),
                Payline(.straightFlush, 10),
                Payline(.fourOfAKind, 4),
                Payline(.fullHouse, 3),
                Payline(.flush, 2),
                Payline(.straight, 2),
                Payline(.threeKind, 1),
            ], estimatedReturn: 101.29, wildCardNumber: CardNumber.deuce),
            PaySchedule(gameID: .looseDeuces, base: deucesWildBase, overrides: [
                Payline(.royalFlushNoDeuces, 250, 4000),
                Payline(.fourDeuces, 500),
                Payline(.royalFlushWithDeuce, 25),
                Payline(.fiveOfAKind, 15),
                Payline(.straightFlush, 10),
                Payline(.fourOfAKind, 4),
                Payline(.fullHouse, 3),
                Payline(.flush, 2),
                Payline(.straight, 2),
                Payline(.threeKind, 1),
            ], estimatedReturn: 100.97, wildCardNumber: CardNumber.deuce),
            PaySchedule(gameID: .looseDeuces, base: deucesWildBase, overrides: [
                Payline(.royalFlushNoDeuces, 250, 4000),
                Payline(.fourDeuces, 500),
                Payline(.royalFlushWithDeuce, 25),
                Payline(.fiveOfAKind, 12),
                Payline(.straightFlush, 11),
                Payline(.fourOfAKind, 4),
                Payline(.fullHouse, 3),
                Payline(.flush, 2),
                Payline(.straight, 2),
                Payline(.threeKind, 1),
            ], estimatedReturn: 100.47, wildCardNumber: CardNumber.deuce),
            PaySchedule(gameID: .looseDeuces, base: deucesWildBase, overrides: [
                Payline(.royalFlushNoDeuces, 250, 4000),
                Payline(.fourDeuces, 500),
                Payline(.royalFlushWithDeuce, 25),
                Payline(.fiveOfAKind, 15),
                Payline(.straightFlush, 18),
                Payline(.fourOfAKind, 4),
                Payline(.fullHouse, 3),
                Payline(.flush, 2),
                Payline(.straight, 2),
                Payline(.threeKind, 1),
            ], estimatedReturn: 100.15, wildCardNumber: CardNumber.deuce),
            PaySchedule(gameID: .looseDeuces, base: deucesWildBase, overrides: [
                Payline(.royalFlushNoDeuces, 250, 4000),
                Payline(.fourDeuces, 500),
                Payline(.royalFlushWithDeuce, 25),
                Payline(.fiveOfAKind, 12),
                Payline(.straightFlush, 10),
                Payline(.fourOfAKind, 4),
                Payline(.fullHouse, 3),
                Payline(.flush, 2),
                Payline(.straight, 2),
                Payline(.threeKind, 1),
            ], estimatedReturn: 100.02, wildCardNumber: CardNumber.deuce),
            PaySchedule(gameID: .looseDeuces, base: deucesWildBase, overrides: [
                Payline(.royalFlushNoDeuces, 250, 4000),
                Payline(.fourDeuces, 500),
                Payline(.royalFlushWithDeuce, 25),
                Payline(.fiveOfAKind, 15),
                Payline(.straightFlush, 7),
                Payline(.fourOfAKind, 4),
                Payline(.fullHouse, 3),
                Payline(.flush, 2),
                Payline(.straight, 2),
                Payline(.threeKind, 1),
            ], estimatedReturn: 99.78, wildCardNumber: CardNumber.deuce),
            PaySchedule(gameID: .looseDeuces, base: deucesWildBase, overrides: [
                Payline(.royalFlushNoDeuces, 250, 4000),
                Payline(.fourDeuces, 500),
                Payline(.royalFlushWithDeuce, 25),
                Payline(.fiveOfAKind, 15),
                Payline(.straightFlush, 6),
                Payline(.fourOfAKind, 4),
                Payline(.fullHouse, 3),
                Payline(.flush, 2),
                Payline(.straight, 2),
                Payline(.threeKind, 1),
            ], estimatedReturn: 99.42, wildCardNumber: CardNumber.deuce),
        ]),
        Game(id: .superAces, name: "Super Aces", solverFilename: "Bonus.dat", schedules: [
            PaySchedule(gameID: .superAces, base: bonusPokerBase, overrides: [
                Payline(.royalFlush, 250, 4000),
                Payline(.straightFlush, 60),
                Payline(.fourAces, 400),
                Payline(.four2s3s4s, 80),
                Payline(.four5sThruKings, 50),
                Payline(.fullHouse, 8),
                Payline(.flush, 5),
                Payline(.straight, 4),
                Payline(.threeKind, 3),
                Payline(.twoPair, 1),
                Payline(.jacksOrBetter, 1),
            ], estimatedReturn: 99.94, wildCardNumber: 0),
            PaySchedule(gameID: .superAces, base: bonusPokerBase, overrides: [
                Payline(.royalFlush, 250, 4000),
                Payline(.straightFlush, 50),
                Payline(.fourAces, 400),
                Payline(.four2s3s4s, 80),
                Payline(.four5sThruKings, 50),
                Payline(.fullHouse, 8),
                Payline(.flush, 5),
                Payline(.straight, 4),
                Payline(.threeKind, 3),
                Payline(.twoPair, 1),
                Payline(.jacksOrBetter, 1),
            ], estimatedReturn: 99.84, wildCardNumber: 0),
            PaySchedule(gameID: .superAces, base: bonusPokerBase, overrides: [
                Payline(.royalFlush, 250, 4000),
                Payline(.straightFlush, 60),
                Payline(.fourAces, 400),
                Payline(.four2s3s4s, 80),
                Payline(.four5sThruKings, 50),
                Payline(.fullHouse, 7),
                Payline(.flush, 5),
                Payline(.straight, 4),
                Payline(.threeKind, 3),
                Payline(.twoPair, 1),
                Payline(.jacksOrBetter, 1),
            ], estimatedReturn: 98.85, wildCardNumber: 0),
            PaySchedule(gameID: .superAces, base: bonusPokerBase, overrides: [
                Payline(.royalFlush, 250, 4000),
                Payline(.straightFlush, 50),
                Payline(.fourAces, 400),
                Payline(.four2s3s4s, 80),
                Payline(.four5sThruKings, 50),
                Payline(.fullHouse, 7),
                Payline(.flush, 5),
                Payline(.straight, 4),
                Payline(.threeKind, 3),
                Payline(.twoPair, 1),
                Payline(.jacksOrBetter, 1),
            ], estimatedReturn: 98.75, wildCardNumber: 0),
            PaySchedule(gameID: .superAces, base: bonusPokerBase, overrides: [
                Payline(.royalFlush, 250, 4000),
                Payline(.straightFlush, 40),
                Payline(.fourAces, 400),
                Payline(.four2s3s4s, 80),
                Payline(.four5sThruKings, 40),
                Payline(.fullHouse, 8),
                Payline(.flush, 5),
                Payline(.straight, 4),
                Payline(.threeKind, 3),
                Payline(.twoPair, 1),
                Payline(.jacksOrBetter, 1),
            ], estimatedReturn: 98.30, wildCardNumber: 0),
        ]),
        Game(id: .tripleDblBonus, name: "Triple Double Bonus", solverFilename: "TDBonus.dat", schedules: [
            PaySchedule(gameID: .tripleDblBonus, base: tripleDoubleBonusBase, overrides: [
                Payline(.royalFlush, 400, 4000),
                Payline(.fourAcesWith234, 400, 4000),
                Payline(.four2s3s4sWithAce234, 400),
                Payline(.fourAces, 160),
                Payline(.four2s3s4s, 80),
                Payline(.four5sThruKings, 50),
                Payline(.straightFlush, 50),
                Payline(.fullHouse, 9),
                Payline(.flush, 7),
                Payline(.straight, 4),
                Payline(.threeKind, 2),
                Payline(.twoPair, 1),
                Payline(.jacksOrBetter, 1),
            ], estimatedReturn: 99.58, wildCardNumber: 0),
            PaySchedule(gameID: .tripleDblBonus, base: tripleDoubleBonusBase, overrides: [
                Payline(.royalFlush, 400, 4000),
                Payline(.fourAcesWith234, 400, 4000),
                Payline(.four2s3s4sWithAce234, 400),
                Payline(.fourAces, 160),
                Payline(.four2s3s4s, 80),
                Payline(.four5sThruKings, 50),
                Payline(.straightFlush, 50),
                Payline(.fullHouse, 8),
                Payline(.flush, 7),
                Payline(.straight, 4),
                Payline(.threeKind, 2),
                Payline(.twoPair, 1),
                Payline(.jacksOrBetter, 1),
            ], estimatedReturn: 98.54, wildCardNumber: 0),
            PaySchedule(gameID: .tripleDblBonus, base: tripleDoubleBonusBase, overrides: [
                Payline(.royalFlush, 400, 4000),
                Payline(.fourAcesWith234, 400, 4000),
                Payline(.four2s3s4sWithAce234, 400),
                Payline(.fourAces, 160),
                Payline(.four2s3s4s, 80),
                Payline(.four5sThruKings, 50),
                Payline(.straightFlush, 50),
                Payline(.fullHouse, 9),
                Payline(.flush, 6),
                Payline(.straight, 4),
                Payline(.threeKind, 2),
                Payline(.twoPair, 1),
                Payline(.jacksOrBetter, 1),
            ], estimatedReturn: 98.15, wildCardNumber: 0),
            PaySchedule(gameID: .tripleDblBonus, base: tripleDoubleBonusBase, overrides: [
                Payline(.royalFlush, 400, 4000),
                Payline(.fourAcesWith234, 400, 4000),
                Payline(.four2s3s4sWithAce234, 400),
                Payline(.fourAces, 160),
                Payline(.four2s3s4s, 80),
                Payline(.four5sThruKings, 50),
                Payline(.straightFlush, 50),
                Payline(.fullHouse, 8),
                Payline(.flush, 6),
                Payline(.straight, 4),
                Payline(.threeKind, 2),
                Payline(.twoPair, 1),
                Payline(.jacksOrBetter, 1),
            ], estimatedReturn: 97.11, wildCardNumber: 0),
            PaySchedule(gameID: .tripleDblBonus, base: tripleDoubleBonusBase, overrides: [
                Payline(.royalFlush, 400, 4000),
                Payline(.fourAcesWith234, 400, 4000),
                Payline(.four2s3s4sWithAce234, 400),
                Payline(.fourAces, 160),
                Payline(.four2s3s4s, 80),
                Payline(.four5sThruKings, 50),
                Payline(.straightFlush, 50),
                Payline(.fullHouse, 9),
                Payline(.flush, 5),
                Payline(.straight, 4),
                Payline(.threeKind, 2),
                Payline(.twoPair, 1),
                Payline(.jacksOrBetter, 1),
            ], estimatedReturn: 97.02, wildCardNumber: 0),
        ]),
        Game(id: .whiteHotAces, name: "White Hot Aces", solverFilename: "Bonus.dat", schedules: [
            PaySchedule(gameID: .whiteHotAces, base: bonusPokerBase, overrides: [
                Payline(.royalFlush, 250, 4000),
                Payline(.straightFlush, 100),
                Payline(.fourAces, 240),
                Payline(.four2s3s4s, 120),
                Payline(.four5sThruKings, 50),
                Payline(.fullHouse, 9),
                Payline(.flush, 5),
                Payline(.straight, 4),
                Payline(.threeKind, 3),
                Payline(.twoPair, 1),
                Payline(.jacksOrBetter, 1),
            ], estimatedReturn: 99.80, wildCardNumber: 0),
            PaySchedule(gameID: .whiteHotAces, base: bonusPokerBase, overrides: [
                Payline(.royalFlush, 250, 4000),
                Payline(.straightFlush, 80),
                Payline(.fourAces, 240),
                Payline(.four2s3s4s, 120),
                Payline(.four5sThruKings, 50),
                Payline(.fullHouse, 9),
                Payline(.flush, 5),
                Payline(.straight, 4),
                Payline(.threeKind, 3),
                Payline(.twoPair, 1),
                Payline(.jacksOrBetter, 1),
            ], estimatedReturn: 99.57, wildCardNumber: 0),
            PaySchedule(gameID: .whiteHotAces, base: bonusPokerBase, overrides: [
                Payline(.royalFlush, 250, 4000),
                Payline(.straightFlush, 50),
                Payline(.fourAces, 240),
                Payline(.four2s3s4s, 120),
                Payline(.four5sThruKings, 50),
                Payline(.fullHouse, 9),
                Payline(.flush, 5),
                Payline(.straight, 4),
                Payline(.threeKind, 3),
                Payline(.twoPair, 1),
                Payline(.jacksOrBetter, 1),
            ], estimatedReturn: 99.24, wildCardNumber: 0),
            PaySchedule(gameID: .whiteHotAces, base: bonusPokerBase, overrides: [
                Payline(.royalFlush, 250, 4000),
                Payline(.straightFlush, 80),
                Payline(.fourAces, 240),
                Payline(.four2s3s4s, 120),
                Payline(.four5sThruKings, 50),
                Payline(.fullHouse, 8),
                Payline(.flush, 5),
                Payline(.straight, 4),
                Payline(.threeKind, 3),
                Payline(.twoPair, 1),
                Payline(.jacksOrBetter, 1),
            ], estimatedReturn: 99.50, wildCardNumber: 0),
            PaySchedule(gameID: .whiteHotAces, base: bonusPokerBase, overrides: [
                Payline(.royalFlush, 250, 4000),
                Payline(.straightFlush, 50),
                Payline(.fourAces, 240),
                Payline(.four2s3s4s, 120),
                Payline(.four5sThruKings, 50),
                Payline(.fullHouse, 8),
                Payline(.flush, 5),
                Payline(.straight, 4),
                Payline(.threeKind, 3),
                Payline(.twoPair, 1),
                Payline(.jacksOrBetter, 1),
            ], estimatedReturn: 98.16, wildCardNumber: 0),
            PaySchedule(gameID: .whiteHotAces, base: bonusPokerBase, overrides: [
                Payline(.royalFlush, 250, 4000),
                Payline(.straightFlush, 80),
                Payline(.fourAces, 240),
                Payline(.four2s3s4s, 120),
                Payline(.four5sThruKings, 50),
                Payline(.fullHouse, 7),
                Payline(.flush, 5),
                Payline(.straight, 4),
                Payline(.threeKind, 3),
                Payline(.twoPair, 1),
                Payline(.jacksOrBetter, 1),
            ], estimatedReturn: 97.44, wildCardNumber: 0),
            PaySchedule(gameID: .whiteHotAces, base: bonusPokerBase, overrides: [
                Payline(.royalFlush, 250, 4000),
                Payline(.straightFlush, 50),
                Payline(.fourAces, 240),
                Payline(.four2s3s4s, 120),
                Payline(.four5sThruKings, 50),
                Payline(.fullHouse, 7),
                Payline(.flush, 5),
                Payline(.straight, 4),
                Payline(.threeKind, 3),
                Payline(.twoPair, 1),
                Payline(.jacksOrBetter, 1),
            ], estimatedReturn: 97.11, wildCardNumber: 0),
        ]),
    ]
}
